- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Start Apache Webserver
    command: systemctl start httpd.service
  - name: Enable Apache on system reboot
    service: name=httpd enabled=yes
