- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Start Apache Webserver
    ansible.builtin.service:
     name: httpd
     state: started
    register: result-status

  - name: Enable Apache on system reboot
    service: name=httpd enabled=yes
    register: result-enable

  - debug:
        msg: "Apache Status {{result-status}} & {{result-enable }}"
