- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Install Apache Webserver
    ansible.builtin.service:
      name: httpd
      state: stopped
   
  - name: Enable Apache on system reboot
    service: name=httpd enabled=yes
