- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Install Apache Webserver
    ansible.builtin.service:
      name: httpd
      state: stopped
   
  - name: Disable Apache on system
    service: name=httpd enabled=false
