- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Stop Apache Webserver
    ansible.builtin.service:
      name: httpd
      state: stopped
    register: result0
   
  - name: Disable Apache Webserver
    service: name=httpd enabled=false
    register: result1

  - name: Apache Status
        ansible.builtin.debug:
          msg:
          - "{{ result0.state}}"
          - "{{ result1.status.ActiveState }}"
