- hosts: all
  remote_user: root
  become: true

  tasks:  
  - name: Stop Apache Webserver
    ansible.builtin.service:
      name: httpd
      state: stopped
    register: result
   
  - name: Disable Apache Webserver
    service: name=httpd enabled=false

  - name: Apache Status
    debug:
      var: result.state
